name: list_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  flutter_bloc: ^8.1.5
  get_it: ^7.2.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  equatable: ^2.0.5
  build_runner: ^2.4.10

flutter:

  uses-material-design: true
